appname: "logcount"
entrypoints:
  celery:
    cmd: "rqworker low"
  command:
    cmd: "python main.py"
  web:
    cmd: "python app.py"
    ports:
      - "5000/tcp"
build:
  - "pip install -r requirements.txt"
meta:
  version: "20150823"
