appname: "logcount"
entrypoints:
  command:
    cmd: "python main.py logcount.intra.hunantv.com:8889"
  web:
    cmd: "python app.py"
    ports:
      - "5000/tcp"
build:
  - "pip install -r requirements.txt"
meta:
  version: "20150823"
