appname: "logcount"
entrypoints:
  celery:
      cmd: "celery multi start 2 -A log.logdeal -c 10 -l warning"
  command:
    cmd: "python main.py"
  web:
    cmd: "python app.py"
    ports:
      - "5000/tcp"
build:
  - "pip install -r requirements.txt"
meta:
  version: "20150823"
